[package]
name = "ssspam-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
prost = "0.12.3"
ssspam-bot = { path = "../ssspam-bot" }
